query GetProtocols {
  protocols {
    id
    name
    description
    form {
      id
      name
    }
    productType
  }
}

mutation CreateProtocol($input: CreateProtocolInput!) {
  createProtocol(input: $input) {
    id
    name
    description
    form {
      id
      name
    }
    productType
  }
}

mutation UpdateProtocol($id: ID!, $input: UpdateProtocolInput!) {
  updateProtocol(id: $id, input: $input) {
    id
    name
    description
    form {
      id
      name
    }
    productType
  }
}

mutation DeleteProtocol($id: ID!) {
  deleteProtocol(id: $id)
}
