query GetUsers {
  users {
    _id
    name
    email
    role
  }
}

mutation CreateUser($createUserInput: CreateUserInput!) {
  createUser(createUserInput: $createUserInput) {
    user {
      _id
      name
      email
      role
    }
  }
}

mutation UpdateUserByAdmin($id: String!, $updateUserInput: UpdateUserInput!) {
  updateUserByAdmin(id: $id, updateUserInput: $updateUserInput) {
    _id
    name
    email
    role
  }
}

mutation DeleteUser($id: String!) {
  deleteUser(id: $id)
}
