mutation CreateInstitution($createInstitutionInput: CreateInstitutionInput!) {
  createInstitution(createInstitutionInput: $createInstitutionInput) {
    id
    name
    address
    phone
    email
  }
}
