mutation CreateSubmission($input: CreateSubmissionInput!) {
  createSubmission(input: $input) {
    id
    practice {
      id
    }
    protocol {
      id
    }
    formData
    locationData
    score
    feedback
    createdAt
    updatedAt
  }
}
