mutation CreateProtocol($input: CreateProtocolInput!) {
  createProtocol(input: $input) {
    id
    name
    description
    forms {
      id
      name
    }
    productType
    createdAt
    updatedAt
  }
}
