mutation CreateSubmission($input: CreateSubmissionInput!) {
  createSubmission(input: $input) {
    id
    group {
      id
    }
    protocol {
      id
    }
    students {
      id
    }
    formData
    score
    feedback
    createdAt
    updatedAt
  }
}
