mutation CreateForm($createFormInput: CreateFormInput!) {
  createForm(createFormInput: $createFormInput) {
    _id
    name
    fields {
      type
      label
      value
      variableName
      placeholder
      hint
      height
      required
      chapter
      question
      questionNumber
      consistencyCondition
      inconsistencyMessage
      errorType
      description
      requirementLevel
      options {
        label
        value
      }
      disabled
      readonly
      name
      specificType
      color
      rules
    }
    createdBy {
      name
      email
    }
    createdAt
  }
}
