mutation CreateSubmission($createSubmissionInput: CreateSubmissionInput!) {
  submitProtocol(createSubmissionInput: $createSubmissionInput) {
    _id
    formId
    data
    submittedBy
    createdAt
  }
}