mutation CreateProtocol($createProtocolInput: CreateProtocolInput!) {
  createProtocol(createProtocolInput: $createProtocolInput) {
    _id
    name
    module
    forms { # Seleccionar los campos del formulario
      _id
      name
      # Otros campos de Form que necesites, ej: fields { ... }
    }
    createdBy
    createdAt
  }
}
