mutation CreateForm($input: CreateFormInput!) {
  createForm(input: $input) {
    id
    name
    description
    fields {
      name
      label
      type
      options
      rules
    }
    createdAt
    updatedAt
  }
}
