mutation CreateCourse($createCourseInput: CreateCourseInput!) {
  createCourse(createCourseInput: $createCourseInput) {
    _id
    name
    institution
    assignedGroups
    createdBy {
      sub
      name
      email
    }
    createdAt
  }
}
