mutation CreateProtocol($createProtocolInput: CreateProtocolInput!) {
  createProtocol(createProtocolInput: $createProtocolInput) {
    _id
    courseId
    name
    module
    formId
    createdAt
  }
}
