query Form($id: String!) {
  form(id: $id) {
    _id
    name
    fields {
      type
      label
      value
      variableName
      placeholder
      hint
      height
      required
      chapter
      question
      questionNumber
      consistencyCondition
      inconsistencyMessage
      errorType
      description
      requirementLevel
      dataSource
      multiple
      options {
        label
        value
      }
      color
      name
      disabled
      readonly
      specificType
      rules
    }
    createdBy {
      name
      email
    }
    createdAt
  }
}