query Form($id: ID!) {
  form(id: $id) {
    id
    name
    description
    version
    fields {
      id
      name
      label
      type
      options
      rules
      defaultValue
      value
      variableName
      hint
      required
      chapter
      question
      questionNumber
      consistencyCondition
      inconsistencyMessage
      errorType
      description
      disabled
      readonly
      dataSource
      placeholder
      specificType
      height
      multiple
      color
      variant
      fontWeight
      textAlign
      textDecoration
      textTransform
      tag
    }
    createdAt
    updatedAt
  }
}