query group($id: ID!) {
  group(id: $id) {
    id
    name
    period
    practice {
      id
      name
      protocols {
        id
        name
        forms {
          id
          name
          description
        }
      }
    }
    tutor {
      id
      firstName
      lastName
    }
    students {
      id
      firstName
      lastName
    }
    institutions {
      id
      name
    }
    deadlines {
      id
      protocol {
        id
      }
      endDate
    }
  }
}