query groupsByStudent($studentId: ID!) {
  groupsByStudent(studentId: $studentId) {
    id
    name
    period
    practice {
      id
      name
    }
    tutor {
      id
      name
    }
    students {
      id
      name
    }
    institutions {
      id
      name
    }
    createdAt
    updatedAt
  }
}