query myGroups {
  myGroups {
    id
    name
    period
    practice {
      id
      name
    }
    tutor {
      id
      firstName
      lastName
    }
    students {
      id
      firstName
      lastName
    }
    institutions {
      id
      name
    }
    createdAt
    updatedAt
  }
}