query PracticeQuery($id: ID!) {
  practice(id: $id) {
    id
    course {
      id
      name
      description
      startDate
      endDate
    }
    student {
      id
      name
      email
    }
    teacher {
      id
      name
      email
    }
    status
    protocols {
      id
      name
      description
      form {
        id
        name
      }
      productType
    }
    submissions {
      id
      formData
      locationData
      score
      feedback
      createdAt
      updatedAt
    }
    createdAt
    updatedAt
  }
}
