query PracticesByTeacherQuery($teacherId: ID!) {
  practicesByTeacher(teacherId: $teacherId) {
    id
    course {
      id
      name
    }
    student {
      id
      name
    }
    teacher {
      id
      name
    }
    status
    protocols {
      id
      name
    }
    submissions {
      id
    }
    createdAt
    updatedAt
  }
}
