query Protocol($id: String!) {
  protocol(id: $id) {
    _id
    name
    description # <-- Añadido
    module
    forms { # Seleccionar los campos del formulario
      _id
      name
      # Otros campos de Form que necesites, ej: fields { ... }
    }
    createdBy
    createdAt
  }
}
