# queries/protocol.gql
query Protocol($id: String!) {
  protocol(id: $id) {
    _id
    courseId
    name
    module
    formId
    createdBy
    createdAt
    attendanceRecords {
      week
      date
      topic
      hours
      group
      classType
      other
      advisorSignature
      tutorSignature
      observations
    }
  }
}
