query submissionsByStudentAndGroup($studentId: ID!, $groupId: ID!) {
  submissionsByStudentAndGroup(studentId: $studentId, groupId: $groupId) {
    id
    protocol {
      id
    }
    form {
      id
      name
    }
    evaluationStatus
    score
    feedback
    createdAt
    updatedAt
  }
}
