mutation SubmitProtocol($createSubmissionInput: CreateSubmissionInput!) {
  submitProtocol(createSubmissionInput: $createSubmissionInput) {
    _id
    formId
    protocolId
    data
    createdAt
    submittedBy
  }
}