query SubmissionsByGroup($groupId: ID!) {
  submissionsByGroup(groupId: $groupId) {
    id
    form {
      id
      name
    }
    students {
      id
      firstName
      lastName
    }
    evaluationStatus
    score
    feedback
    createdAt
    updatedAt
  }
}
