query Submissions {
  submissions {
    id
    practice {
      id
      student {
        id
        name
      }
      teacher {
        id
        name
      }
    }
    protocol {
      id
      name
    }
    formData
    locationData
    score
    feedback
    createdAt
    updatedAt
  }
}
