query Submission($id: ID!) {
  submission(id: $id) {
    id
    practice {
      id
      student {
        id
        name
      }
      teacher {
        id
        name
      }
    }
    protocol {
      id
      name
      form {
        id
        name
        fields {
          name
          label
          type
          options
          rules
        }
      }
    }
    formData
    locationData
    score
    feedback
    createdAt
    updatedAt
  }
}