query Submission($id: ID!) {
  submission(id: $id) {
    id
    group {
      id
      name
    }
    protocol {
      id
      name
    }
    students {
      id
      firstName
      lastName
    }
    form {
      id
      name
      description
      fields {
        id
      }
    }
    formData
    score
    feedback
    createdAt
    updatedAt
  }
}
