mutation UpdateInstitution($updateInstitutionInput: UpdateInstitutionInput!) {
  updateInstitution(updateInstitutionInput: $updateInstitutionInput) {
    id
    name
    address
    phone
    email
  }
}
