mutation UpdatePractice($updatePracticeInput: UpdatePracticeInput!) {
  updatePractice(updatePracticeInput: $updatePracticeInput) {
    _id
    student {
      _id
      name
    }
    advisor {
      _id
      name
    }
    protocol {
      _id
      name
      module
      forms {
        _id
        name
      }
    }
    institutionName
    courseName
    status
    filledForms {
      form {
        _id
        name
      }
      submission {
        _id
      }
    }
    createdBy {
      _id
      name
    }
    createdAt
  }
}