mutation UpdatePractice($updatePracticeInput: UpdatePracticeInput!) {
  updatePractice(updatePracticeInput: $updatePracticeInput) {
    id
    name
    description
    protocols {
      id
      name
    }
  }
}
