mutation updatePractice($id: ID!, $input: UpdatePracticeInput!) {
  updatePractice(id: $id, updatePracticeInput: $input) {
    id
    name
    description
    protocols {
      id
      name
    }
  }
}
