mutation UpdateProtocol($id: ID!, $input: UpdateProtocolInput!) {
  updateProtocol(id: $id, input: $input) {
    id
    name
    description
    forms {
      id
      name
    }
    productType
    createdAt
    updatedAt
  }
}