mutation updateGroup($id: ID!, $input: UpdateGroupInput!) {
  updateGroup(id: $id, input: $input) {
    id
    name
    period
    practice {
      id
      name
    }
    tutor {
      id
      name
    }
    students {
      id
      name
    }
    institutions {
      id
      name
    }
  }
}