mutation UpdateForm($id: ID!, $input: UpdateFormInput!) {
  updateForm(id: $id, input: $input) {
    id
    name
    description
    fields {
      name
      label
      type
      options
      rules
    }
    createdAt
    updatedAt
  }
}
