import { FormFieldType } from "@/types";
import type { AvailableElementDefinition } from "@/types";

export const availableElements: AvailableElementDefinition[] = [
  {
    name: "Text Input",
    type: FormFieldType.TEXT,
    displayName: "Text Input",
    icon: "mdi-form-textbox",
    defaultConfig: {
      name: "text_input",
      label: "Text Input",
      type: FormFieldType.TEXT,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "text",
    },
  },
  {
    name: "Text Area",
    type: FormFieldType.TEXTAREA,
    displayName: "Text Area",
    icon: "mdi-form-textarea",
    defaultConfig: {
      name: "textarea",
      label: "Text Area",
      type: FormFieldType.TEXTAREA,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "textarea",
      height: "4",
    },
  },
  {
    name: "Dropdown Select",
    type: FormFieldType.SELECT,
    displayName: "Dropdown Select",
    icon: "mdi-form-dropdown",
    defaultConfig: {
      name: "select",
      label: "Select Option",
      type: FormFieldType.SELECT,
      options: { items: ["Option 1", "Option 2", "Option 3"] },
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      dataSource: "",
      multiple: false,
    },
  },
  {
    name: "Date Picker",
    type: FormFieldType.DATE,
    displayName: "Date Picker",
    icon: "mdi-calendar",
    defaultConfig: {
      name: "date_picker",
      label: "Select Date",
      type: FormFieldType.DATE,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    name: "Map Input",
    type: FormFieldType.MAP,
    displayName: "Map Input",
    icon: "mdi-map",
    defaultConfig: {
      name: "map_input",
      label: "Location",
      type: FormFieldType.MAP,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "File Upload",
    type: FormFieldType.FILE_UPLOAD,
    displayName: "File Upload",
    icon: "mdi-file-upload",
    defaultConfig: {
      name: "file_upload",
      label: "Upload File",
      type: FormFieldType.FILE_UPLOAD,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Checkbox",
    type: FormFieldType.CHECKBOX,
    displayName: "Checkbox",
    icon: "mdi-checkbox-marked",
    defaultConfig: {
      name: "checkbox",
      label: "Checkbox",
      type: FormFieldType.CHECKBOX,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Date Picker (JSON)",
    type: FormFieldType.DATE_PICKER,
    displayName: "Date Picker (JSON)",
    icon: "mdi-calendar-range",
    defaultConfig: {
      name: "date_picker",
      label: "Date",
      type: FormFieldType.DATE_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    name: "Radio Group",
    type: FormFieldType.RADIO_GROUP,
    displayName: "Radio Group",
    icon: "mdi-radiobox-marked",
    defaultConfig: {
      name: "radio_group",
      label: "Radio Options",
      type: FormFieldType.RADIO_GROUP,
      options: { items: ["Option A", "Option B"] },
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Time Picker",
    type: FormFieldType.TIME_PICKER,
    displayName: "Time Picker",
    icon: "mdi-clock-time-four-outline",
    defaultConfig: {
      name: "time_picker",
      label: "Select Time",
      type: FormFieldType.TIME_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "HH:MM",
    },
  },
  {
    name: "Button",
    type: FormFieldType.BUTTON,
    displayName: "Button",
    icon: "mdi-button-cursor",
    defaultConfig: {
      name: "button",
      label: "Button",
      type: FormFieldType.BUTTON,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      color: "primary",
    },
  },
];
