import { FormFieldType } from "@/types";
import type { AvailableElementDefinition } from "@/types";

export const availableElements: AvailableElementDefinition[] = [
  {
    name: "Typography Heading",
    type: FormFieldType.TYPOGRAPHY_HEADING,
    displayName: "Typography Heading",
    icon: "mdi-format-title",
    defaultConfig: {
      name: "typography_heading",
      label: "Heading",
      value: "Heading Text",
      type: FormFieldType.TYPOGRAPHY_HEADING,
      variant: "text-h4",
      fontWeight: "font-weight-bold",
      textAlign: "text-left",
      textDecoration: "text-decoration-none",
      textTransform: "text-none",
      tag: "h4",
    },
  },
  {
    name: "Typography Body",
    type: FormFieldType.TYPOGRAPHY_BODY,
    displayName: "Typography Body",
    icon: "mdi-format-text-variant",
    defaultConfig: {
      name: "typography_body",
      label: "Body Text",
      value: "Body text content.",
      type: FormFieldType.TYPOGRAPHY_BODY,
      variant: "text-body-1",
      fontWeight: "font-weight-regular",
      textAlign: "text-left",
      textDecoration: "text-decoration-none",
      textTransform: "text-none",
      tag: "p",
    },
  },
  {
    name: "Text Input",
    type: FormFieldType.TEXT,
    displayName: "Text Input",
    icon: "mdi-form-textbox",
    defaultConfig: {
      name: "text_input",
      label: "Text Input",
      type: FormFieldType.TEXT,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "text",
    },
  },
  {
    name: "Text Area",
    type: FormFieldType.TEXTAREA,
    displayName: "Text Area",
    icon: "mdi-form-textarea",
    defaultConfig: {
      name: "textarea",
      label: "Text Area",
      type: FormFieldType.TEXTAREA,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "textarea",
      height: "4",
    },
  },
  {
    name: "Select Simple",
    type: FormFieldType.SELECT_SIMPLE,
    displayName: "Select Simple",
    icon: "mdi-form-dropdown",
    defaultConfig: {
      name: "select_simple",
      label: "Select Simple",
      type: FormFieldType.SELECT_SIMPLE,
      options: [
        { label: "Option 1", value: "option1" },
        { label: "Option 2", value: "option2" },
        { label: "Option 3", value: "option3" },
      ],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      multiple: false,
    },
  },
  {
    name: "Select DataSource",
    type: FormFieldType.SELECT_DYNAMIC,
    displayName: "Select DataSource",
    icon: "mdi-database-search",
    defaultConfig: {
      name: "select_dynamic",
      label: "Select Dinámico",
      type: FormFieldType.SELECT_DYNAMIC,
      options: { items: [] },
      rules: [],
      value: "",
      variableName: "",
      hint: "Selecciona una fuente de datos en el editor",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      dataSource: "",
      multiple: false,
    },
  },
  {
    name: "Date Input",
    type: FormFieldType.DATE_INPUT,
    displayName: "Date Input",
    icon: "mdi-calendar",
    defaultConfig: {
      name: "date_input",
      label: "Date",
      type: FormFieldType.DATE_INPUT,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    name: "Date Picker",
    type: FormFieldType.DATE_PICKER,
    displayName: "Date Picker",
    icon: "mdi-calendar-month-outline",
    defaultConfig: {
      name: "date_picker",
      label: "Select Date",
      type: FormFieldType.DATE_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    name: "Map Input",
    type: FormFieldType.MAP,
    displayName: "Map Input",
    icon: "mdi-map",
    defaultConfig: {
      name: "map_input",
      label: "Location",
      type: FormFieldType.MAP,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "File Upload",
    type: FormFieldType.FILE_UPLOAD,
    displayName: "File Upload",
    icon: "mdi-file-upload",
    defaultConfig: {
      name: "file_upload",
      label: "Upload File",
      type: FormFieldType.FILE_UPLOAD,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Checkbox",
    type: FormFieldType.CHECKBOX,
    displayName: "Checkbox",
    icon: "mdi-checkbox-marked",
    defaultConfig: {
      name: "checkbox",
      label: "Checkbox",
      type: FormFieldType.CHECKBOX,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Checkbox Group",
    type: FormFieldType.CHECKBOX_GROUP,
    displayName: "Checkbox Group",
    icon: "mdi-checkbox-multiple-marked-outline",
    defaultConfig: {
      name: "checkbox_group",
      label: "Checkbox Group",
      type: FormFieldType.CHECKBOX_GROUP,
      options: [
        { label: "Option 1", value: "option1", isOtherOption: false },
        { label: "Option 2", value: "option2", isOtherOption: false },
        { label: "Other", value: "other", isOtherOption: true },
      ],
      rules: [],
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Radio Group",
    type: FormFieldType.RADIO_GROUP,
    displayName: "Radio Group",
    icon: "mdi-radiobox-marked",
    defaultConfig: {
      name: "radio_group",
      label: "Radio Group",
      type: FormFieldType.RADIO_GROUP,
      options: [
        { label: "Option 1", value: "option1", isOtherOption: false },
        { label: "Option 2", value: "option2", isOtherOption: false },
        { label: "Other", value: "other", isOtherOption: true },
      ],
      rules: [],
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Time Picker",
    type: FormFieldType.TIME_PICKER,
    displayName: "Time Picker",
    icon: "mdi-clock-time-four-outline",
    defaultConfig: {
      name: "time_picker",
      label: "Select Time",
      type: FormFieldType.TIME_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "HH:MM",
    },
  },
  {
    name: "Button",
    type: FormFieldType.BUTTON,
    displayName: "Button",
    icon: "mdi-button-cursor",
    defaultConfig: {
      name: "button",
      label: "Button",
      type: FormFieldType.BUTTON,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      color: "primary",
    },
  },
  {
    name: "Repeater",
    type: FormFieldType.REPEATER,
    displayName: "Repeater",
    icon: "mdi-view-list",
    defaultConfig: {
      name: "repeater",
      label: "Repeater Field",
      type: FormFieldType.REPEATER,
      value: "",
      options: [
        { name: "edad", label: "Edad", type: "TEXT", specificType: "number" },
        { name: "grado", label: "Grado", type: "TEXT" },
      ],
      rules: [],
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    name: "Radio Matrix",
    type: FormFieldType.RADIOMATRIX,
    displayName: "Radio Matrix",
    icon: "mdi-checkbox-multiple-marked",
    defaultConfig: {
      name: "radio_matrix",
      label: "Radio Matrix",
      type: FormFieldType.RADIOMATRIX,
      options: {
        items: ["Item 1", "Item 2", "Item 3"],
        columns: [
          { text: "Option A", value: "A" },
          { text: "Option B", value: "B" },
          { text: "Option C", value: "C" },
        ],
      },
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
];
