import { FormFieldType } from "@/types";

export interface FormField {
  name: string;
  label: string;
  type: FormFieldType | string;
  options?: Record<string, any> | any[];
  rules?: string[];
  defaultValue?: string;
  value?: any;
  variableName?: string;
  hint?: string;
  required?: boolean;
  chapter?: string;
  question?: string;
  questionNumber?: string;
  consistencyCondition?: string;
  inconsistencyMessage?: string;
  errorType?: string;
  description?: string;
  disabled?: boolean;
  readonly?: boolean;
  dataSource?: string;
  multiple?: boolean;
  placeholder?: string;
  specificType?: string;
  height?: string;
  color?: string;
}

export interface AvailableElementDefinition {
  type: FormFieldType;
  displayName: string;
  icon: string;
  defaultConfig: Omit<FormField, "name">;
}

export const availableElements: AvailableElementDefinition[] = [
  {
    type: FormFieldType.TEXT,
    displayName: "Text Input",
    icon: "mdi-form-textbox",
    defaultConfig: {
      label: "Text Input",
      type: FormFieldType.TEXT,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "text",
    },
  },
  {
    type: FormFieldType.TEXTAREA,
    displayName: "Text Area",
    icon: "mdi-form-textarea",
    defaultConfig: {
      label: "Text Area",
      type: FormFieldType.TEXTAREA,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "",
      specificType: "textarea",
      height: "4",
    },
  },
  {
    type: FormFieldType.SELECT,
    displayName: "Dropdown Select",
    icon: "mdi-form-dropdown",
    defaultConfig: {
      label: "Select Option",
      type: FormFieldType.SELECT,
      options: { items: ["Option 1", "Option 2", "Option 3"] },
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      dataSource: "",
      multiple: false,
    },
  },
  {
    type: FormFieldType.DATE,
    displayName: "Date Picker",
    icon: "mdi-calendar",
    defaultConfig: {
      label: "Select Date",
      type: FormFieldType.DATE,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    type: FormFieldType.MAP,
    displayName: "Map Input",
    icon: "mdi-map",
    defaultConfig: {
      label: "Location",
      type: FormFieldType.MAP,
      options: [],
      rules: [],
      value: null,
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    type: FormFieldType.FILE_UPLOAD,
    displayName: "File Upload",
    icon: "mdi-file-upload",
    defaultConfig: {
      label: "Upload File",
      type: FormFieldType.FILE_UPLOAD,
      options: [],
      rules: [],
      value: null,
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    type: FormFieldType.CHECKBOX,
    displayName: "Checkbox",
    icon: "mdi-checkbox-marked",
    defaultConfig: {
      label: "Checkbox",
      type: FormFieldType.CHECKBOX,
      options: [],
      rules: [],
      value: false,
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    type: FormFieldType.DATE_PICKER,
    displayName: "Date Picker (JSON)",
    icon: "mdi-calendar-range",
    defaultConfig: {
      label: "Date",
      type: FormFieldType.DATE_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "YYYY-MM-DD",
    },
  },
  {
    type: FormFieldType.RADIO_GROUP,
    displayName: "Radio Group",
    icon: "mdi-radiobox-marked",
    defaultConfig: {
      label: "Radio Options",
      type: FormFieldType.RADIO_GROUP,
      options: { items: ["Option A", "Option B"] },
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
    },
  },
  {
    type: FormFieldType.TIME_PICKER,
    displayName: "Time Picker",
    icon: "mdi-clock-time-four-outline",
    defaultConfig: {
      label: "Select Time",
      type: FormFieldType.TIME_PICKER,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      placeholder: "HH:MM",
    },
  },
  {
    type: FormFieldType.BUTTON,
    displayName: "Button",
    icon: "mdi-btn",
    defaultConfig: {
      label: "Button",
      type: FormFieldType.BUTTON,
      options: [],
      rules: [],
      value: "",
      variableName: "",
      hint: "",
      required: false,
      chapter: "",
      question: "",
      questionNumber: "",
      consistencyCondition: "",
      inconsistencyMessage: "",
      errorType: "Soft",
      description: "",
      disabled: false,
      readonly: false,
      color: "primary",
    },
  },
];
